<a href="https://colab.research.google.com/github/Jorayala/Colab/blob/master/Linear_equations_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Importamos libreria Numpy

In [2]:
import numpy as np

Ingresamos un sistema de ecuaciones lineales

In [ ]:
A = np.array([
        [2, 5, 1, 1],
        [1, 2, -1, -1],
        [-1, 2, 2, 2],
        [1, -1, 2, 1]
    ], dtype=np.dtype(float))
b = np.array([6, 3, 14, 8], dtype=np.dtype(float))


Ahora usamos Numpy

In [ ]:
# determinant of matrix A
d = None
d = np.linalg.det(A)
# solution of the system of linear equations
# with the corresponding coefficients matrix A and free coefficients b
x = None
x = np.linalg.solve(A, b)


print(f"Determinant of matrix A: {d:.2f}")

print(f"Solution vector: {x}")

Determinant of matrix A: -11.00
Solution vector: [ -7.81818182   4.63636364  22.         -23.54545455]


Ahora multiplicacion de matrices, Mathematically, matrix multiplication is defined only if number of the columns of matrix 𝐴
 is equal to the number of the rows of matrix  𝐵

In [4]:
C = np.array([[4, 9, 9], [9, 1, 6], [9, 2, 3]])
print("Matrix C (3 by 3):\n", C)

D = np.array([[2, 2], [5, 7], [4, 4]])
print("Matrix D (3 by 2):\n", D)

Matrix C (3 by 3):
 [[4 9 9]
 [9 1 6]
 [9 2 3]]
Matrix D (3 by 2):
 [[2 2]
 [5 7]
 [4 4]]


In [5]:
np.matmul(C, D)

array([[ 89, 107],
       [ 47,  49],
       [ 40,  44]])

In [6]:
C @ D

array([[ 89, 107],
       [ 47,  49],
       [ 40,  44]])

Ahora linear transformation

In [ ]:
import numpy as np
# OpenCV library for image transformations.
import cv2

In [3]:
M = np.array([[1, 2, -1], [1, 0, 1], [0, 1, 0]])
print("Matrix C (3 by 3):\n", M)

Matrix C (3 by 3):
 [[ 1  2 -1]
 [ 1  0  1]
 [ 0  1  0]]


In [5]:
np.linalg.det(M)

-2.0

In [6]:
np.linalg.inv(M)

array([[ 0.5,  0.5, -1. ],
       [-0. , -0. ,  1. ],
       [-0.5,  0.5,  1. ]])

In [8]:
v1 = np.array([3, 1, -7])

v2 = np.array([2, 2, 0])

In [9]:
v1@v2

8

In [10]:
X = np.array([[5, 2, 3], [-1, -3, 2], [0, 1, -1]])
print("Matrix C (3 by 3):\n", X)
Y = np.array([[1, 0, -4], [2, 1, 0], [8, -1, 0]])
print("Matrix C (3 by 3):\n", Y)

Matrix C (3 by 3):
 [[ 5  2  3]
 [-1 -3  2]
 [ 0  1 -1]]
Matrix C (3 by 3):
 [[ 1  0 -4]
 [ 2  1  0]
 [ 8 -1  0]]


In [14]:
X@Y


array([[ 33,  -1, -20],
       [  9,  -5,   4],
       [ -6,   2,   0]])

In [15]:
np.linalg.det(np.linalg.inv(X@Y))


0.0